---
ID: "3ab1fbd3-b6ce-4e8d-b3df-5bec8eecf259"
Parent: "63e5565e-7399-4bc8-82fc-c0faf8c9e84f"
Template: "ff9d70eb-44cb-4777-b9ee-3308041928ce"
Path: /sitecore/system/Modules/Reports/Configuration/Viewer/ItemSecurity
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20090605T161738
    - ID: "2fe97449-f425-4789-ab93-c246bfa1749b"
      Hint: Columns
      Value: |
        <Columns><Column name="locked by">Locked by</Column><Column name="workflow">Workflow</Column></Columns>
    - ID: "49eb5881-0aea-4d84-9850-1f8a9a2183fe"
      Hint: Class
      Value: Sitecore.Feature.Reports.Viewers.ItemViewer
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "60acfb3b-d34d-43d8-8b57-86d26b30dd5a"
      Hint: Attributes
      Value: 
    - ID: "6fb5beba-ecd8-4b56-b20a-bf292193d491"
      Hint: Assembly
      Value: Sitecore.Feature.Reports
